name: Update League Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache R Packages
      uses: actions/cache@v3
      with:
        path: ~/R/library
        key: r-${{ hashFiles('**/DESCRIPTION') }}-${{ runner.os }}
        restore-keys: r-${{ runner.os }}

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install Dependencies
      run: |
        install.packages('jsonlite', repos = 'http://cran.rstudio.com/')
        install.packages('devtools', repos = 'http://cran.rstudio.com/')
        devtools::install_github("JaseZiv/worldfootballR")
        install.packages('dplyr', repos = 'http://cran.rstudio.com/')

    - name: Fetch and Save League Tables
      run: Rscript fetch_league_tables.R

    - name: Commit and Push if Changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Automatically update soccer statistics"
        git push
