name: Update League Tables

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron:  '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages('devtools')"
        Rscript -e "devtools::install_github('JaseZiv/worldfootballR')"
        Rscript -e "install.packages(c('dplyr', 'jsonlite'))"

    - name: Fetch league tables and save as JSON
      run: Rscript fetch_league_tables.R

    - name: Commit and push updates
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update league tables" || echo "No changes to commit"
        git push
