name: Update League Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to v3 for the latest version

    - name: Setup R
      uses: r-lib/actions/setup-r@v2 # Updated to v2

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages('devtools')"
        Rscript -e "devtools::install_github('JaseZiv/worldfootballR')"
        Rscript -e "install.packages(c('dplyr', 'jsonlite'))"

    - name: Fetch league tables and save as JSON
      run: Rscript fetch_league_tables.R

    - name: Commit changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Automatically update soccer statistics" || echo "No changes to commit"
        git push
