name: Update League Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # This is already the latest version

    - name: Setup cache for R packages
      uses: actions/cache@v3
      with:
        path: |
          ~/R/x86_64-pc-linux-gnu-library/4.1  # Example path, adjust the version as needed
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/*.R') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e "install.packages(c('devtools', 'dplyr', 'jsonlite'), repos = 'http://cran.rstudio.com/')"
        Rscript -e "devtools::install_github('JaseZiv/worldfootballR')"

    - name: Fetch league tables and save as JSON
      run: Rscript fetch_league_tables.R

    - name: Commit changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automatically update soccer statistics" -a || echo "No changes to commit"
        git push
