name: Update League Tables

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup cache for R packages
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '.Rhistory') }}
        restore-keys: ${{ runner.os }}-r-

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
        if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
        if (!requireNamespace("jsonlite", quietly = TRUE)) install.packages("jsonlite")
        if (!requireNamespace("worldfootballR", quietly = TRUE)) devtools::install_github("JaseZiv/worldfootballR")

    - name: Fetch league tables and save as JSON
      run: Rscript fetch_league_tables.R

    - name: Commit changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "GitHub Actions"
        git diff --quiet && git diff --staged --quiet || (git add -A && git commit -m "Automatically update soccer statistics")
        git push
